module CommonTypedefs {
    typedef octet ByteType;
    typedef long IntType;
    typedef unsigned long UIntType;
    typedef long long LLongType;
    typedef unsigned long long ULLongType;
    typedef float FloatType;
    typedef double DoubleType;
    typedef string IdentifierType;
    typedef string URI;
    typedef sequence<long> LongArrayType;
    
    // Bounded sequence typedefs
    typedef sequence<char, 256> ShortString;
    typedef sequence<octet, 1024> ByteBuffer;
};

module CommonEnums {
    enum StatusCode {
        STATUS_OK,
        STATUS_ERROR,
        STATUS_WARNING
    };
    
    // Bitmask example
    bitmask Flags {
        FLAG_READ,
        FLAG_WRITE,
        FLAG_EXECUTE,
        FLAG_HIDDEN
    };
};

module CommonStructs {
    struct BaseStruct {
        long id;
        string name;
    };
    
    struct ExtendedStruct : BaseStruct {
        long extraField;
        double value;
    };
    
    struct FinalStruct : ExtendedStruct {
        string description;
    };
    
    // Struct with all primitive types
    struct AllPrimitives {
        boolean boolVal;
        octet byteVal;
        char charVal;
        short shortVal;
        unsigned short ushortVal;
        long longVal;
        unsigned long ulongVal;
        long long llongVal;
        unsigned long long ullongVal;
        float floatVal;
        double doubleVal;
        string stringVal;
    };
    
    // Struct with sequence fields
    struct ContainerStruct {
        sequence<long> intList;
        sequence<string> stringList;
        sequence<BaseStruct> structList;
    };
};

module CommonUnions {
    enum BaseKind {
        KIND_A,
        KIND_B,
        KIND_C
    };
    
    union BaseUnion switch (BaseKind) {
        case KIND_A: long valueA;
        case KIND_B: string valueB;
        case KIND_C: double valueC;
    };
    
    union ExtendedUnion switch (BaseKind) {
        case KIND_A: long valueA;
        case KIND_B: string valueB;
        default: double defaultValue;
    };
    
    // Union with integer discriminator
    union IntDiscrimUnion switch (long) {
        case 1: string text;
        case 2: long number;
        default: double decimal;
    };
};

module CommonTypedefs2 {
    typedef CommonStructs::BaseStruct BaseStructAlias;
    typedef CommonStructs::ExtendedStruct ExtendedStructAlias;
    typedef CommonUnions::BaseUnion BaseUnionAlias;
    typedef string URI;
    typedef string URL;
    typedef unsigned long long DateTime;
    
    // Typedef of sequence
    typedef sequence<CommonStructs::BaseStruct, 100> BaseStructList;
    typedef sequence<CommonUnions::BaseUnion> UnionList;
};
