// Simplified IDL Test File for CycloneDDS

#include "common_types.idl"

module Shapes {
    
    struct Point {
        @key long x;
        @key long y;
    };
    
    struct Circle {
        @key long id;
        Point center;
        double radius;
        string color;
        sequence<double> points;
    };
    
    // Use typedef from another module
    struct TypedefCircle {
        @key CommonTypedefs2::BaseStructAlias id;
        Circle circle;
        CommonTypedefs2::URI href;
        CommonTypedefs2::DateTime timestamp;
    };
    
    // Use inheritance from another module
    struct ExtendedCircle : Circle {
        string label;
        CommonTypedefs::IdentifierType identifier;
    };
    
    struct Rectangle {
        @key long id;
        Point top_left;
        Point bottom_right;
        string label;
    };
    
    // Use nested inheritance
    struct FinalCircle : CommonStructs::FinalStruct {
        Circle circle;
    };
    
    enum ShapeType {
        CIRCLE_TYPE,
        RECTANGLE_TYPE,
        TRIANGLE_TYPE
    };
    
    union ShapeValue switch (ShapeType) {
        case CIRCLE_TYPE: Circle circle;
        case RECTANGLE_TYPE: Rectangle rectangle;
        default: string description;
    };
    
    // Use union typedef from another module
    struct UnionHolder {
        CommonTypedefs2::BaseUnionAlias unionField;
        CommonUnions::ExtendedUnion extendedUnion;
    };
};
